version: "2"
services:
  rabbit-1:
    hostname: rabbit-1
    container_name: rabbit-1
    image: rabbitmq:3.11.3-management
    ports:
      - "5672:5672"
      - "8101:15672"
      # - "5672:5672"
      # - "15672:15672"
      # - "15691:15691"
      # - "15692:15692"
    volumes:
      - "/srv/rabbitmq/config/rabbit-1/:/config/"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE="YYRDITCRAERCUROGWFMZ"
    networks:
      - rabbitmq
# healthcheck:
#   test: ["CMD", "curl", "-f", "http://localhost"]
#   interval: 1m30s
#   timeout: 10s
#   retries: 3
#   start_period: 40s


  rabbit-2:
    hostname: rabbit-2
    container_name: rabbit-2
    image: rabbitmq:3.11.3-management
    ports:
      - "5672:5672"
      - "8102:15672"
    volumes:
      - "/srv/rabbitmq/config/rabbit-2/:/config/"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE="YYRDITCRAERCUROGWFMZ"
    networks:
      - rabbitmq
    depends_on:
      - rabbit-1



  rabbit-3:
    hostname: rabbit-3
    container_name: rabbit-3
    image: rabbitmq:3.11.3-management
    ports:
      - "5672:5672"
      - "8103:15672"
    volumes:
      - "/srv/rabbitmq/config/rabbit-3/:/config/"
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE="YYRDITCRAERCUROGWFMZ"
    networks:
      - rabbitmq
    depends_on:
      - rabbit-2
networks:
  rabbitmq:
    external:
      name: rabbitmq
